---
- name: stop postgres
  service: 
    name: postgresql.service
    state: stopped

- name: delete main
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  file:
    path: "{{ postgres_data_dir }}/main"
    state: absent

- name: create new main
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  file:
    path: "{{ postgres_data_dir }}/main"
    state: directory
    mode: go-rwx

- name: backup
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  command: "pg_basebackup -P -R -X stream -c fast -h {{ item }} -U postgres -D {{ postgres_data_dir }}/main"
  environment:
    PGPASSWORD: "{{ postgres_password }}"
  with_items: "{{ postgres_master_address }}"
  notify: "Restart postgres"
