- name: Clone the django-locallibrary tutorial
  hosts: app
  become: yes
  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clone MDN Django local library tutorial
      git:
        repo: "https://github.com/mdn/django-locallibrary-tutorial.git"
        dest: "/home/vagrant/django-locallibrary"
        version: main
- name: Deploy Django local library in Docker
  hosts: app
  become: yes
  tasks:
    - name: Pull timurbabs/django image
      docker_image:
        name: "timurbabs/django"
        source: pull

    - name: Run django_app container
      docker_container:
        name: "django_app"
        image: "timurbabs/django"
        state: started
        ports:
          - "8000:8000"
        # Если хотим прокинуть локальный код внутрь контейнера:
        volumes:
          - "/home/vagrant/django-locallibrary:/app"