---
- name: "Loki | Create Loki group"
  become: true
  group:
    name: "{{ loki_group }}"
    system: yes
    state: present

- name: "Loki | Create Loki user"
  become: true
  user:
    name: "{{ loki_user.name }}"
    group: "{{ loki_group }}"
    system: yes
    shell: "{{ loki_user.shell }}"
    state: present

- name: "Loki | Create systemd Loki Service"
  become: true
  template:
    src: "{{ loki_service.template_path }}"
    dest: "/etc/systemd/system/{{ loki_service.name }}"
    mode: '0644'
    owner: 'root'
    group: 'root'
  notify: "Loki | Start and Enable Loki Service"
