roles:
  - src: https://gitlab.com/devops9824703/docker-role.git
    version: main
    name: docker
  - src: https://gitlab.com/devops9824703/prometheus-role.git
    version: main
    name: prometheus
  - src: https://gitlab.com/devops9824703/grafana-role.git
    version: main
    name: grafana
  - src: https://gitlab.com/devops9824703/loki-role.git
    version: main
    name: loki