Vagrant.configure("2") do |config|

  # Машина для приложения
  config.vm.define "app" do |app|
    app.vm.box = "ubuntu/jammy64"
    app.vm.hostname = "app"
    app.vm.network "private_network", ip: "192.168.56.10"
  end

  # Машина для мониторинга
  config.vm.define "monitoring" do |mon|
    mon.vm.box = "ubuntu/jammy64"
    mon.vm.hostname = "monitoring"
    mon.vm.network "private_network", ip: "192.168.56.11"
  end

end
